version: '3'

services:

  codenize-tools:
    image: kiriake/codenize-tools
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_TOKEN
      - AWS_REGION
    volumes:
      - ${PWD}:/src
    working_dir: /src
